#!/usr/bin/env python

import os, time, sys

sys.path.append("/home/jeroen/Software/PythonDaemon")
sys.path.append("/home/jeroen/Software/ConnectFour/")

from Daemon import * 
from Webserver import *

class ConnectFourWebserver(Daemon):
    def __init__(self):
         Daemon.__init__(self, "ConnectFourWebserver")

         server = tornado.httpserver.HTTPServer(ConnectFourWebServer())
         server.listen(8080)
         self._instance = tornado.ioloop.IOLoop.instance()

    def run(self):
         self._instance.start()

    def cleanup(self):
         self._instance.stop()

if __name__ == "__main__":
    daemon = ConnectFourWebserver()
    if len(sys.argv) == 2:
         if 'start' == sys.argv[1]:
              daemon.start()
         elif 'stop' == sys.argv[1]:
              daemon.stop()
         elif 'restart' == sys.argv[1]:
              daemon.restart()
         else:
              print "Unknown command"
              sys.exit(2)
         sys.exit(0)
    else:
         print "usage: %s start|stop|restart" % sys.argv[0]
         sys.exit(2)

