#!/usr/bin/env python
### BEGIN INIT INFO
# Provides:         Starts Webserver for ConnectFour game 
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
# Author: Jeroen Andreß https://github.com/jeroen-andress

import os, time, sys

from Daemon import * 
from Webserver import *

class ConnectFourWebserver(Daemon):
    def __init__(self):
         Daemon.__init__(self, "ConnectFourWebserver")
         self._instance = None

    def _createInstance(self):
         server = tornado.httpserver.HTTPServer(ConnectFourWebServer())
         server.listen(8080)
         self._instance = tornado.ioloop.IOLoop.instance()

    def run(self):
         if self._instance is None:
              self._createInstance()
         self._instance.start()

    def cleanup(self):
         if not self._instance is None:
              self._instance.stop()

if __name__ == "__main__":
    daemon = ConnectFourWebserver()
    if len(sys.argv) == 2:
         if 'start' == sys.argv[1]:
              daemon.start()
         elif 'stop' == sys.argv[1]:
              daemon.stop()
         elif 'restart' == sys.argv[1]:
              daemon.restart()
         else:
              print "Unknown command"
              sys.exit(2)
         sys.exit(0)
    else:
         print "usage: %s start|stop|restart" % sys.argv[0]
         sys.exit(2)

